sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

test:
  provider: script
  script: "./mvnw clean test"
  skip_cleanup: true

deploySnapshot:
  branches:
    only:
    - master
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && ./mvnw verify -Dgpg.passphrase=$GPG_PASSPHRASE -DskipTests deploy"
