name: Release and Deploy

on:
  push:
    branches:
      - 'release'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts    

      - name: Release
        run: |
          git config user.email "pazonec@yandex.ru"
          git config --global user.name "Pavel Zorin"
          ./mvnw -B -DskipTests release:clean release:prepare release:perform
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          MAVEN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
